version: "3.8"

services:
  rabbitmq:
    image: rabbitmq:3-management
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest
    networks:
      - mq-net
    deploy:
      replicas: 1
      placement:
        constraints:
          - node.role == manager

  producer:
    image: 211.183.3.10:5000/producer:latest
    networks:
      - mq-net
    deploy:
      replicas: 2
      restart_policy:
        condition: on-failure

  consumer:
    image: 211.183.3.10:5000/consumer:latest
    networks:
      - mq-net
    deploy:
      replicas: 2
      restart_policy:
        condition: on-failure

networks:
  mq-net:
    driver: overlay

